site_name: seize the day
nav:
  - 随笔日记:
    - 25:
      - 25/06.md









theme:
  name: material
  language: zh
  icon:
    logo: material/book
  font:
    text: Roboto
  palette:
      scheme: slate
      accent: indigo
      primary: black
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
