site_name: Wangzhichao
nav:
  - 随笔日记:
    - 2025:
        - 随笔日记/2025/19.md









theme:
  name: material
  language: zh
  icon:
    logo: material/book
  font:
    text: Roboto
  palette:
      scheme: slate
      accent: indigo
      primary: black
